### PR TITLE
Add Simplified Chinese translate

### PR DESCRIPTION
**Pull request by fishheadsam**
Just translate few document.

### CODE REVIEW

**Comment by albar965** [comment]
Thank you but wait a bit before continuing on the documents. I'm working on the update for the version 2.4 branch and there are quite a few changes in the manual.
Alex

**Comment by albar965** [comment]
Do you have plans to translate the whole manual or the application?
Alex

**Comment by fishheadsam** [comment]
Yes! I'd love to and I want translate manual first, I need time to learn QT.

Alexander Barthel <notifications@github.com<mailto:notifications@github.com>> 于 2019年10月1日星期二 15:06写道：

Do you have plans to translate the whole manual or the application?
Alex

**Comment by albar965** [comment]
You don't need to learn Qt for translating the application. Only the Qt Linguist. 
I suppose you've already seen the Wiki: https://github.com/albar965/littlenavmap/wiki/Translating

I'll let you know when the update for the new 2.4 manual is finished.
Alex

**Comment by fishheadsam** [comment]
Thanks for giving me information. I will keep translate and wait 2.4 version release.

Regards,
Zed Yu


Alexander Barthel <notifications@github.com<mailto:notifications@github.com>> 于 2019年10月2日星期三 18:46写道：

You don't need to learn Qt for translating the application. Only the Qt Linguist.
I suppose you've already seen the Wiki: https://github.com/albar965/littlenavmap/wiki/Translating

I'll let you know when the update for the new 2.4 manual is finished.
Alex

**Comment by albar965** [comment]
I just merged all your changes to the 2.4 release branch which contains the latest changes. I'll merge these back to master once the release stuff is over.
But for now you can start your work based on `release/2.4`.

The UI translation is more important than the manual IMHO but I leave that up to you. You just have to consider the Chinese or English buttons and menu items which are referenced in the manual.

And thank you for contributing!

Alex

**Comment by fishheadsam** [comment]
Hi Alex,

Thank you for your update. Don’t worry about the UI, I will handle it, I’m a student and I need split time for this. I will try to let more Chinese player know this software and it might help for the translate.

Thanks again for you bring us this wonderful software!

Regards,
Zed

________________________________
发件人: Alexander Barthel <notifications@github.com>
发送时间: Wednesday, October 9, 2019 10:06:09 PM
收件人: albar965/littlenavmap-manual <littlenavmap-manual@noreply.github.com>
抄送: fishheadsam <fishheadsam@outlook.com>; Author <author@noreply.github.com>
主题: Re: [albar965/littlenavmap-manual] Add Simplified Chinese translate (#8)


I just merged all your changes to the 2.4 release branch which contains the latest changes. I'll merge these back to master once the release stuff is over.
But for now you can start your work based on release/2.4.

The UI translation is more important than the manual IMHO but I leave that up to you. You just have to consider the Chinese or English buttons and menu items which are referenced in the manual.

And thank you for contributing!

Alex

―

**Pull request merged**
